//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.ZimVie.Wcs.ZWCS.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.ZimVie.Wcs.ZWCS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   入荷日を入力して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00001 {
            get {
                return ResourceManager.GetString("zwce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷日[{0}]は、既にユーザー[{1}]が[{2}]に登録を完了しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00002 {
            get {
                return ResourceManager.GetString("zwce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の出荷通知データを取り込んで下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00003 {
            get {
                return ResourceManager.GetString("zwce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先を選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00004 {
            get {
                return ResourceManager.GetString("zwce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付を選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00005 {
            get {
                return ResourceManager.GetString("zwce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なビジネスロジックが検出されました。システム管理者に連絡して下さい。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00006 {
            get {
                return ResourceManager.GetString("zwce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題は検出されませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00007 {
            get {
                return ResourceManager.GetString("zwce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力パラメーターがNULL参照、または不足しています。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00008 {
            get {
                return ResourceManager.GetString("zwce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷通知データ登録に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00009 {
            get {
                return ResourceManager.GetString("zwce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図データ生成と登録に登録に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00010 {
            get {
                return ResourceManager.GetString("zwce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図ヘッダーデータ生成と登録に登録に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00011 {
            get {
                return ResourceManager.GetString("zwce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図明細データ生成と登録に登録に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00012 {
            get {
                return ResourceManager.GetString("zwce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品目マスタから、複数品目に対する添付文書管理番号群の取得に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00013 {
            get {
                return ResourceManager.GetString("zwce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図ヘッダーテーブルからの既存指図番号の現在最大値取得に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00014 {
            get {
                return ResourceManager.GetString("zwce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図ヘッダーテーブルへの登録が失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00015 {
            get {
                return ResourceManager.GetString("zwce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図明細データ生成に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00016 {
            get {
                return ResourceManager.GetString("zwce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図における、ヘッダーデータと明細データに不整合が発生しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00017 {
            get {
                return ResourceManager.GetString("zwce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図明細データ登録に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00018 {
            get {
                return ResourceManager.GetString("zwce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図ヘッダーとPO番号の関連データを登録に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00019 {
            get {
                return ResourceManager.GetString("zwce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指示エクセルファイルの構造に問題が検出されました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00020 {
            get {
                return ResourceManager.GetString("zwce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図ヘッダーとPO番号の関連データ生成に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00021 {
            get {
                return ResourceManager.GetString("zwce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図番号のフォーマットに不正が検知されました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00022 {
            get {
                return ResourceManager.GetString("zwce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図エクセルファイルの生成に失敗しました。対象作業指図番号：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00023 {
            get {
                return ResourceManager.GetString("zwce00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図エクセルファイルの生成結果に問題が検知されました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00024 {
            get {
                return ResourceManager.GetString("zwce00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}]件の作業指図の生成に成功しました。
        ///保存先ディレクトリ：
        ///{1}
        ///保存されたエクセルファイル：
        ///{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00025 {
            get {
                return ResourceManager.GetString("zwce00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品目マスタラベル情報の取得に失敗しました。品目番号：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00026 {
            get {
                return ResourceManager.GetString("zwce00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業指図明細からのラベルデータ生成に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00027 {
            get {
                return ResourceManager.GetString("zwce00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なラベルデータが検出されました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00028 {
            get {
                return ResourceManager.GetString("zwce00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル印字結果を正しく取得することができませんでした。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00029 {
            get {
                return ResourceManager.GetString("zwce00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}]製品ラベル： セット数[{1}]、枚数合計[{2}]
        ///社内物流ラベル： セット数[{3}]、枚数合計[{4}]
        ///製品ラベル発行済指図：
        ///[{5}]
        ///社内物流ラベル発行済指図：
        ///[{6}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00030 {
            get {
                return ResourceManager.GetString("zwce00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベルプリンターのポートオープンに失敗しました。発生箇所[{0}]、実行結果[{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00031 {
            get {
                return ResourceManager.GetString("zwce00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベルプリンターのOUTPUTコマンドの実行結果に不正が検出されました。発生箇所[{0}]、実行結果[{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00032 {
            get {
                return ResourceManager.GetString("zwce00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なラベルタイプの値が検出されました。発生箇所[{0}]、不正値[{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00033 {
            get {
                return ResourceManager.GetString("zwce00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品目[{0}]は、マスタにてラベル不要（ラベルタイプ = 0）と登録されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00034 {
            get {
                return ResourceManager.GetString("zwce00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベルが正常に印刷されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00035 {
            get {
                return ResourceManager.GetString("zwce00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JANコードーをキーとした、品目マスタからの品目番号取得に失敗しました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00036 {
            get {
                return ResourceManager.GetString("zwce00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つのJANコードーに対し、2つ以上の品目番号が存在しています。品目マスタを修正して下さい。JAN：[{0}]、品目：[{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00037 {
            get {
                return ResourceManager.GetString("zwce00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み取られた指図明細情報の文字列の長さが正しくありせまん。文字列：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00038 {
            get {
                return ResourceManager.GetString("zwce00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み取られたバーコード文字列が、GS1-128のフォーマットと合致していません（GTIN識別子01で始まっていない）。文字列：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00039 {
            get {
                return ResourceManager.GetString("zwce00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み取られたバーコード文字列が、GS1-128のフォーマットと合致していません（長さが19未満）。文字列：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00040 {
            get {
                return ResourceManager.GetString("zwce00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み取られたバーコード文字列が、GS1-128のフォーマットと合致していません（ロット識別子10が所定の位置にない）。文字列：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00041 {
            get {
                return ResourceManager.GetString("zwce00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み取られたバーコード文字列から、製品番号とロットの取得に失敗しました。文字列：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00042 {
            get {
                return ResourceManager.GetString("zwce00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製品バーコードが、指図明細とラベルで一致していません。
        ///指図明細：[{0}]
        ///ラベル：[{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00043 {
            get {
                return ResourceManager.GetString("zwce00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製品番号が、指図明細のと現物で一致していません。
        ///指図製品番号：[{0}]
        ///旧システム製品番号：[{1}]
        ///仕入先製品番号：[{2}]
        ///現物：[{3}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00044 {
            get {
                return ResourceManager.GetString("zwce00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロット番号が、指図明細と現物で一致していません。
        ///指図明細：[{0}]
        ///現物：[{1}]
        ///
        ///製品番号のスキャンからやり直して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00045 {
            get {
                return ResourceManager.GetString("zwce00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指図明細の製品数量が無効です。製品数量：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00046 {
            get {
                return ResourceManager.GetString("zwce00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指図明細に対して、現物との照合を全数をやり直しして下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00047 {
            get {
                return ResourceManager.GetString("zwce00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製品番号が、指図明細のと現物で一致していません。
        ///指図製品番号：[{0}]
        ///現物：[{1}]
        ///旧システム製品番号：[品目マスタに値なし]
        ///仕入先製品番号：[品目マスタに値なし] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00048 {
            get {
                return ResourceManager.GetString("zwce00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品目マスタの更新と新規登録において、異常が感知されました。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00049 {
            get {
                return ResourceManager.GetString("zwce00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不要な入力パラメーターが設定されています。発生箇所：[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00050 {
            get {
                return ResourceManager.GetString("zwce00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZWCS品目マスタからの、最新更新時刻取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00051 {
            get {
                return ResourceManager.GetString("zwce00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZWCS品目マスタ更新履歴の登録に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00052 {
            get {
                return ResourceManager.GetString("zwce00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZWCS品目マスタ更新のプロセスにおいて、レコードの一時削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00053 {
            get {
                return ResourceManager.GetString("zwce00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZWCS品目マスタ更新のプロセスにおいて、レコードの新規作成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00054 {
            get {
                return ResourceManager.GetString("zwce00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新されたキントーン品目マスタのレコードに、ZWCSアプリケーションの仕様を満たしていない値が見つかりました：
        ///[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00055 {
            get {
                return ResourceManager.GetString("zwce00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷通知ファイルを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00056 {
            get {
                return ResourceManager.GetString("zwce00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷通知ファイルの形式が不正です。エクセルファイルを使用して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00057 {
            get {
                return ResourceManager.GetString("zwce00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品目マスタレコードの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00058 {
            get {
                return ResourceManager.GetString("zwce00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品目マスタに該当のない品番が出荷通知エクセルファイルに含まれています：
        ///[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00059 {
            get {
                return ResourceManager.GetString("zwce00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品目マスタを使用した品番の照合に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwce00060 {
            get {
                return ResourceManager.GetString("zwce00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指図明細に対して、製品番号とロットの照合が完了ました。
        ///指図番号[{1}]
        ///明細番号[{2}]
        ///数量　　[{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwci00001 {
            get {
                return ResourceManager.GetString("zwci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指図明細の数量と、スキャンした現物の数量一致しました。
        ///指図数量 [{0}]
        ///現物数量 [{0}]
        ///
        ///正しいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwci00002 {
            get {
                return ResourceManager.GetString("zwci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kintoneの品目マスタに、更新または新規登録された品目は見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwci00003 {
            get {
                return ResourceManager.GetString("zwci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kintoneの品目マスタに、新規登録された品目のみ見つかりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwci00004 {
            get {
                return ResourceManager.GetString("zwci00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZWCSの品目マスタに、更新履歴の登録が必要な品目は見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwci00005 {
            get {
                return ResourceManager.GetString("zwci00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kintone品目マスタの変更が、ZWCS品目マスタに反映されました。
        ///更新品目：[{0}]
        ///新規品目：[{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zwci00006 {
            get {
                return ResourceManager.GetString("zwci00006", resourceCulture);
            }
        }
    }
}
